export const MODULE_ROUTES = {
  '/admin/dashboards': 'Dashboard',
  '/admin/tax': 'Tax',
  '/admin/company-origin': 'Company Origin',
  '/admin/service-frequency': 'Service Frequency',
  '/admin/billing-frequency': 'Billing Frequency',
  '/admin/uom': 'Unit Of Measurement',
  '/admin/call-type': 'Call Type',
  '/admin/chemicals': 'Chemicals',
  '/admin/industry': 'Industry',
  '/admin/holidays': 'Holidays',
  '/admin/incident': 'Incident',
  '/admin/todo-items': 'Todo Items',
  '/admin/site-risk': 'Site Risk',
  '/admin/equipments': 'Equipments',
  '/admin/department': 'Department',
  '/admin/designation': 'Designation',
  '/admin/employee-list': 'Employee List',
  '/admin/employee-leave-type': 'Employee Leave Type',
  '/admin/user-privilege': 'User Privilege',
  '/admin/employee-leave': 'Employee Leave',
  '/admin/pests': 'Service Type (Pest)',
  '/admin/customers': 'Customers',
  '/admin/contracts': 'Contracts',
  '/admin/service-request': 'Service Request',
  '/admin/calendar': 'Calendar',
  '/admin/invoice': 'Invoice',
  '/admin/suppliers': 'Suppliers',
  '/admin/stock/material-request': 'Material Request',
  '/admin/stock/report': 'Stock Report',
  '/admin/stock/usage-report': 'Usage Report',
  '/admin/attendance/slots': 'Attendance Slots',
  '/admin/attendance/attendance': 'Attendance',
  '/admin/attendance/schedule': 'Attendance Schedule',
  '/admin/attendance/timesheet': 'Attendance Timesheet',
  '/admin/attendance/payslip-summary': 'Payslip Summary',
  '/admin/view-contract-status': 'View Contract Status',
  '/admin/map': 'Map',
  '/admin/non-pre-schedule': 'Non Pre-Schedule',
  '/admin/backlog-finder': 'Backlog Finder',
  '/admin/followup-finder': 'Followup Finder',
  '/admin/kiv-finder': 'KIV Finder',
  '/admin/productivity-finder': 'Productivity Finder',
  '/admin/service-summary-report': 'Service Summary Report',
  '/admin/ric-followup-report': 'RIC / Follow-up Report',
  '/admin/productivity-summary': 'Productivity Summary',
  '/admin/scdf-report': 'SCDF Report',
  '/admin/sales-report': 'Sales Report',
  '/admin/pest-trending': 'Pest Trending',
  '/admin/customer-audit': 'Customer Audit',
  '/admin/contracts-audit': 'Contracts Audit'
}
