/**
 * Mappings between Backend DB Module Names and Frontend Standard Permission Keys.
 * Key = Backend Module Name (from API/DB)
 * Value = Frontend Standard Key (used in VerticalMenu and usePermission checks)
 */
export const PERMISSION_ALIASES = {
  // Dashboard
  'Dashboard': 'Dashboard',

  // Master
  'Master': 'Master',
  'Master/Tax': 'Tax',
  'Tax': 'Tax',
  'Taxes': 'Tax',
  'Master/Company Origin': 'Company Origin',
  'Master/Company': 'Company Origin',
  'Company Origin': 'Company Origin',
  'Company_origin': 'Company Origin',
  'Master/Service Frequency': 'Service Frequency',
  'Master/Frequency_master': 'Service Frequency',
  'Frequency_master': 'Service Frequency',
  'Service Frequency': 'Service Frequency',
  'Master/Billing Frequency': 'Billing Frequency',
  'Billing Frequency': 'Billing Frequency',
  'Master/UOM': 'Unit Of Measurement',
  'Master/Unit Of Measurement': 'Unit Of Measurement',
  'Master/Unit_Of_Measurement': 'Unit Of Measurement',
  'UOM': 'Unit Of Measurement',
  'Unit Of Measurement': 'Unit Of Measurement',
  'Master/Call Type': 'Call Type',
  'Call Type': 'Call Type',
  'Master/Chemicals': 'Chemicals',
  'Chemicals': 'Chemicals',
  'Master/Industry': 'Industry',
  'Industry': 'Industry',
  'Master/Holidays': 'Holidays',
  'Holidays': 'Holidays',
  'Master/Incident': 'Incident',
  'Incident': 'Incident',
  'Master/Todo Items': 'Todo Items',
  'Todo Items': 'Todo Items',
  'Master/Site Risk': 'Site Risk',
  'Master/Site_Risk': 'Site Risk',
  'Site Risk': 'Site Risk',
  'Master/Equipments': 'Equipments',
  'Equipments': 'Equipments',

  // Employee
  'Department': 'Department',
  'Designation': 'Designation',
  'Employee': 'Employee List',
  'Employee List': 'Employee List',
  'Employee_leave': 'Employee Leave',
  'Employee Leave': 'Employee Leave',
  'Employee Leaves': 'Employee Leave',
  'Employee Leave Type': 'Employee Leave Type',
  'User Privilege': 'User Privilege',
  'Employee/User Privilege': 'User Privilege',
  'Employee/Employee List': 'Employee List',
  'Employee/Department': 'Department',
  'Employee/Designation': 'Designation',
  'Employee/Employee Leave Type': 'Employee Leave Type',
  'Slots': 'Attendance Slots',
  'Schedule': 'Attendance Schedule',

  // Service / Pest
  'Service_types': 'Service Type (Pest)',
  'Service Type Pest': 'Service Type (Pest)',
  'Service Type (Pest)': 'Service Type (Pest)',

  // Contracts
  'Customers': 'Customers',
  'Contracts': 'Contracts',
  'Contract Status': 'Contract Status',
  'View Contract Status': 'View Contract Status',
  'Contracts/Customers': 'Customers',
  'Contracts/Contracts': 'Contracts',

  // Attendance
  'Attendance/Scheduling': 'Attendance Schedule',
  'Attendance/Attendance Schedule': 'Attendance Schedule',
  'Attendance/Schedule': 'Attendance Schedule',
  'Scheduling': 'Attendance Schedule',
  'Attendance Schedule': 'Attendance Schedule',
  'Schedule': 'Attendance Schedule',
  'Attendance/Attendance': 'Attendance',
  'Attendance': 'Attendance',
  'Attendance/Slots': 'Attendance Slots',
  'Attendance/Attendance Slots': 'Attendance Slots',
  'Attendance Slots': 'Attendance Slots',
  'Slots': 'Attendance Slots',
  'Attendance/Payslip Summary': 'Payslip Summary',
  'Attendance/Payslip Summary Report': 'Payslip Summary',
  'Payslip Summary': 'Payslip Summary',
  'Payslip Summary Report': 'Payslip Summary',
  'Attendance/Timesheet': 'Attendance Timesheet',
  'Attendance/Attendance Timesheet': 'Attendance Timesheet',
  'Attendance Timesheet': 'Attendance Timesheet',

  // Operations / Service
  'Service Requests': 'Service Request',
  'Service Request': 'Service Request',
  'Calendar': 'Calendar',
  'Invoice': 'Invoice',
  'Suppliers': 'Suppliers',
  'Operations/Service Request': 'Service Request',
  'Operations/Calendar': 'Calendar',
  'Operations/Invoice': 'Invoice',

  // Purchase
  'Stock/Purchase Order': 'Purchase Order',
  'Purchase/Purchase Order': 'Purchase Order',
  'Purchase Order': 'Purchase Order',
  'Stock/Purchase Inward': 'Purchase Inward',
  'Purchase/Purchase Inward': 'Purchase Inward',
  'Purchase Inward': 'Purchase Inward',
  'Stock/Purchase Return': 'Purchase Return',
  'Purchase/Purchase Return': 'Purchase Return',
  'Purchase Return': 'Purchase Return',

  // Transfer
  'Stock/Transfer Request': 'Transfer Request',
  'Transfer/Transfer Request': 'Transfer Request',
  'Transfer Request': 'Transfer Request',
  'Stock/Transfer In': 'Transfer In',
  'Transfer/Transfer In': 'Transfer In',
  'Transfer In': 'Transfer In',
  'Stock/Transfer Out': 'Transfer Out',
  'Transfer/Transfer Out': 'Transfer Out',
  'Transfer Out': 'Transfer Out',

  // Stock
  'Stock/Suppliers': 'Suppliers',
  'Stock/Material Request': 'Material Request',
  'Material Request': 'Material Request',
  'Stock/Stock Report': 'Stock Report',
  'Stock Report': 'Stock Report',
  'Stock/Usage Report': 'Usage Report',
  'Usage Report': 'Usage Report',
  'Stock/Stock Summary': 'Stock Summary',
  'Stock Summary': 'Stock Summary',
  'Stock/Material Usage': 'Material Usage',
  'Material Usage': 'Material Usage',

  // Finder
  'Finder/Non Pre-Schedule': 'Non Pre-Schedule',
  'Non Pre-Schedule': 'Non Pre-Schedule',
  'Finder/Backlog Finder': 'Backlog Finder',
  'Backlog Finder': 'Backlog Finder',
  'Finder/Followup Finder': 'Followup Finder',
  'Followup Finder': 'Followup Finder',
  'Finder/KIV Finder': 'KIV Finder',
  'KIV Finder': 'KIV Finder',
  'Finder/Productivity Finder': 'Productivity Finder',
  'Productivity Finder': 'Productivity Finder',

  // Reports
  'Reports/Service Summary Report': 'Service Summary Report',
  'Service Summary Report': 'Service Summary Report',
  'Reports/RIC Report': 'RIC / Follow-up Report',
  'Reports/RIC / Follow-up Report': 'RIC / Follow-up Report',
  'RIC Report': 'RIC / Follow-up Report',
  'RIC Follow-up Report': 'RIC / Follow-up Report',
  'RIC Followup Report': 'RIC / Follow-up Report',
  'RIC / Follow-up Report': 'RIC / Follow-up Report',
  'Reports/Productivity Summary': 'Productivity Summary',
  'Productivity Summary': 'Productivity Summary',
  'Reports/SCDF Report': 'SCDF Report',
  'SCDF Report': 'SCDF Report',
  'Reports/Sales Report': 'Sales Report',
  'Sales Report': 'Sales Report',
  'Reports/Pest Trending': 'Pest Trending',
  'Pest Trending': 'Pest Trending',

  // Sales
  'Sales/Quotation': 'Sales Quotation',
  'Sales/Proposal Item': 'Proposal Item',
  'Sales/Proposal_item': 'Proposal Item',
  'Sales/Quotation_master': 'Sales Quotation',

  // Audit
  'Audit/Customer Audit': 'Customer Audit',
  'Customer Audit': 'Customer Audit',
  'Audit/Contract Audit': 'Contracts Audit',
  'Audit/Contracts Audit': 'Contracts Audit',
  'Contract Audit': 'Contracts Audit',
  'Contracts Audit': 'Contracts Audit',

  // Map
  'Map': 'Map'
}
